import { recursiveFn } from 'ch3/ex3111/recursiveFn.js';

recursiveFn();

console.log('手前で例外が送出されるため、到達しません。');
